package com.tanvi.healthpal.ui.qrscanner.model

data class NutriscoreData(
    val energy: Double,
    val energy_points: Double,
    val energy_value: Double,
    val fiber: Double,
    val fiber_points: Double,
    val fiber_value: Double,
    val fruits_vegetables_nuts_colza_walnut_olive_oils: Double,
    val fruits_vegetables_nuts_colza_walnut_olive_oils_points: Double,
    val fruits_vegetables_nuts_colza_walnut_olive_oils_value: Double,
    val grade: String,
    val is_beverage: Double,
    val is_cheese: Double,
    val is_fat: Double,
    val is_water: Double,
    val negative_points: Double,
    val positive_points: Double,
    val proteins: Double,
    val proteins_points: Double,
    val proteins_value: Double,
    val saturated_fat: Double,
    val saturated_fat_points: Double,
    val saturated_fat_ratio: Double,
    val saturated_fat_ratio_points: Double,
    val saturated_fat_ratio_value: Double,
    val saturated_fat_value: Double,
    val score: Double,
    val sodium: Double,
    val sodium_points: Double,
    val sodium_value: Double,
    val sugars: Double,
    val sugars_points: Double,
    val sugars_value: Double
)